### ISSUE TITLE
Add check for java 7 before deploying to bintray (gradle bintray plugin)

### ISSUE THREAD

**Issue by tbarker9** [ysb33r/Gradle#2]
If you try to deploy to bintray with java 6 and below, you get a cryptic error related to the http basic credential.  To alleviate confusion, throw a GrailsException("You need java 7 to upload to bintray")

**Comment by ysb33r** [comment]
I believe this has been addressed. If you think you still need to check for this then please raise a new issue over on https://github.com/ysb33r/bintrayissues
